databases:
  - name: lms-db
    plan: free # change if you need bigger capacity

services:
  - type: redis
    name: lms-redis
    plan: free # change if you need more memory

  - type: web
    name: lms-nest
    env: node
    plan: free # or "starter"/"standard"
    # Fixed build command - ensure clean install and successful build
    buildCommand: npm ci && npm run build && echo "Build complete. Contents of dist:" && ls -la dist/
    # Fixed start command - use relative path
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production

      # Postgres connection string (Render injects automatically)
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString

      # Redis URL (Render injects automatically)
      - key: REDIS_URL
        fromService:
          type: redis
          name: lms-redis
          property: connectionString
