databases:
  - name: lms-db
    plan: free

services:
  - type: redis
    name: lms-redis
    plan: free

  - type: web
    name: lms-nest
    env: node
    plan: free
    buildCommand: npm ci && npm run build && echo "=== BUILD DEBUG ===" && ls -la && echo "=== DIST CONTENTS ===" && ls -la dist/ && echo "=== MAIN.JS EXISTS? ===" && ls -la dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lms-redis
          property: connectionString
