databases:
  - name: lms-db
    plan: free

services:
  - type: redis
    name: lms-redis
    plan: free

  - type: web
    name: lms-nest
    env: node
    plan: free
    buildCommand: |
      echo "=== Installing dependencies ===" &&
      npm ci &&
      echo "=== Building application ===" &&
      npm run build &&
      echo "=== BUILD COMPLETE - Checking outputs ===" &&
      ls -la &&
      echo "=== DIST DIRECTORY ===" &&
      ls -la dist/ &&
      echo "=== CHECKING FOR MAIN.JS ===" &&
      if [ -f "dist/main.js" ]; then
        echo "✅ main.js found"
      else
        echo "❌ main.js NOT found - listing all dist files:"
        find dist -type f -name "*.js" | head -10
      fi
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lms-redis
          property: connectionString
