databases:
  - name: lms-db
    plan: free
    databaseName: lms
    user: lms_user

services:
  - type: redis
    name: lms-redis
    plan: free

  - type: web
    name: lms-nest
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lms-redis
          property: connectionString
